void testNoToken(int level, int showMessage);
void testInitializeFinalize(int level, int showMessage);
void esfuerzoInitializeFinalize(int level, int repeticiones, int showMessage);
void testGetFunctionList(int level, int showMessage);
void esfuerzoGetFunctionList(int level, int repeticiones, int showMessage);
void testGetInfo(int level, int showMessage);
void esfuerzoGetInfo(int level, int repeticiones, int showMessage);
void testGetSlotList(int level, int showMessage);
void esfuerzoGetSlotList(int level, int repeticiones, int showMessage);
void testGetSlotInfo(int level, int showMessage);
void esfuerzoGetSlotInfo(int level, int repeticiones, int showMessage);
void testNoSessionHandle(int level, int showMessage);
void testGetTokenInfo(int level, int showMessage);
void esfuerzoGetTokenInfo(int level, int repeticiones, int showMessage);
void testInitToken(int level, int showMessage);
void esfuerzoInitToken(int level, int repeticiones, int showMessage);
void testOpenSession(int level, int showMessage);
void esfuerzoOpenSession(int level, int repeticiones, int showMessage);
void testCloseSession(int level, int showMessage);
void esfuerzoCloseSession(int level, int repeticiones, int showMessage);
void testCloseAllSessions(int level, int showMessage);
void esfuerzoCloseAllSessions(int level, int repeticiones, int showMessage);
void testSessionHandleNeeded(int level, int showMessage);
void testSessionHandleManagement(int level, int showMessage);
void testGetSessionInfo(int level, int showMessage);
void esfuerzoGetSessionInfo(int level, int repeticiones, int showMessage);
void testInitPin(int level, int showMessage);
void esfuerzoInitPin(int level, int repeticiones, int showMessage);
void testLogin(int level, int showMessage);
void esfuerzoLogin(int level, int repeticiones, int showMessage);
void testLogout(int level, int showMessage);
void esfuerzoLogout(int level, int repeticiones, int showMessage);
void testSetPin(int level, int showMessage);
void esfuerzoSetPin(int level, int repeticiones, int showMessage);

void testObjectManagementFunctions(int level, int showMessage);
void testCreateObject(int level, int showMessage);
void esfuerzoCreateObject(int level, int repeticiones, int showMessage);
void testDestroyObject(int level, int showMessage);
void esfuerzoDestroyObject(int level, int repeticiones, int showMessage);
void testGenerateKeyPair(int level, int showMessage);
void esfuerzoGenerateKeyPair(int level, int repeticiones, int showMessage);
void testGetAttributeValue(int level, int showMessage);
void esfuerzoGetAttributeValue(int level, int repeticiones, int showMessage);
void testFindObjectsMechanism(int level, int showMessage);
void esfuerzoFindObjectsMechanism(int level, int repeticiones, int showMessage);

void testMechanisms(int level, int showMessage);
void testSignMechanism(int level, int showMessage);
void esfuerzoSignMechanism(int level, int repeticiones, int showMessage);
void testDigestMechanism(int level, int showMessage);
void esfuerzoDigestMechanism(int level, int repeticiones, int showMessage);

void testRNGFunctions(int level, int showMessage);
void testSeedRandom(int level, int showMessage);
void esfuerzoSeedRandom(int level, int repeticiones, int showMessage);
void testGenerateRandom(int level, int showMessage);
void esfuerzoGenerateRandom(int level, int repeticiones, int showMessage);


